# Site settings
title: Site Title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/standard-jekyll-template"
url: "http://blacktm.com"

# Header
header:
  logo_text: Logo Text
  logo_img: logo.svg
  nav:
    - text: Docs
      link: /docs
    - text: About
      link: /about
    - text: Blog
      link: /blog

# Edit pages
edit_page:
  # enabled: true  # Enabled by default for pages and posts
  text: "Edit this page »"
  github:
    author: blacktm
    repo:   standard-jekyll-template
    branch: gh-pages

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page
